name: Web Agents1

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Web PrivPropRes(Inside)4_2"]
    types:
      - completed

jobs:
  followupjob3:
    runs-on: ubuntu-latest
    concurrency: multirunP1
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      CON_STR: ${{ vars.CON_STR }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install other dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools==57.5.0
          
      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install -r requirements.txt
          # If you want to avoid using the 2to3 tool, ensure that your dependencies are Python 3 compatible.

      - name: Run web scraping
        run: |
          python AgentsPart2.py

